package com.pulsar.marvin.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0A8537)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1F4DE)
val md_theme_light_onPrimaryContainer = Color(0xFF00210A)
val md_theme_light_secondary = Color(0xFF8BAEFF)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001946)
val md_theme_light_tertiary = Color(0xFF8B00DD)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF3E5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2C004D)

val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF9F9F9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFF9F9F9)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DC)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)

val md_theme_dark_primary = Color(0xFF8AD09D)
val md_theme_dark_onPrimary = Color(0xFF003917)
val md_theme_dark_primaryContainer = Color(0xFF005224)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1F4DE)
val md_theme_dark_secondary = Color(0xFFACC7FF)
val md_theme_dark_onSecondary = Color(0xFF002E6C)
val md_theme_dark_secondaryContainer = Color(0xFF004494)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E4FF)
val md_theme_dark_tertiary = Color(0xFFD8B4FF)
val md_theme_dark_onTertiary = Color(0xFF4B007A)
val md_theme_dark_tertiaryContainer = Color(0xFF6A00AC)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3E5FF)

val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
